# Generated by Django 5.0.2 on 2024-09-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_add_article', 'Can add article'), ('can_edit_article', 'Can edit article'), ('can_delete_article', 'Can delete article')]},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_add_comment', 'Can add comment'), ('can_edit_comment', 'Can edit comment'), ('can_delete_comment', 'Can delete comment')]},
        ),
    ]
